Fix the way of getting  Instagram Account ID
TiagoGrosso/instagram-graph-api-lib pull request #69
Opened 2021-07-18 10:44 UTC by andresgutgon

The way Facebook allow to get Instagram Account ID has changed. Now for
the user to be able to use with this lib their Instagram Accounts has to
meet to requirements:
1. Be an Instagram Business Account
2. Be this Instagram Business Account linked to a Facebook page.

This is super annoying and a terrible DX and UX experience. But is the
price to play with a big corp I guess.

So this PR try to fix this lib by adding 2 new endpoints and removing
the old `/me` which is not used anymore.
The new endpoints are
1. `/me/accounts` to get a list of authorized FB pages by the user
   (accessToken)
2. /${facebook-page-id} to get the linked Instagram Business account of
   that page.

This involves some UI thinking. This is what I think I would do:
1. Prompt users to log in with Facebook. Set the needed API permissions
2. When they log in with Facebook and accept necesary permissions I show
   then the name of the pages they authorized. They chose one
3. I do a second request to get the linked Instagram Business Account

For login the user with Facebook on my Node app I'm using [passport-facebook](http://www.passportjs.org/packages/passport-facebook/)

☝️ Those points in code:
``` javascript
import {
  GetAuthorizedFacebookPagesRequest,
  GetAuthorizedFacebookPagesResponse,
  GetLinkedInstagramAccountRequest,
  GetLinkedInstagramAccountResponse,
} from 'instagram-graph-api'

// Get the accessToken from the user.  (Ex.: Using Passport.js in a Node project)

async function getInstagramId (): string | null {
  const pagesRequest: GetAuthorizedFacebookPagesRequest = new GetAuthorizedFacebookPagesRequest(accessToken)
  const pagesResponse: GetAuthorizedFacebookPagesResponse = await pagesRequest.execute()
  // This can be done showing a UI with authorized pages. Here I'm picking the first 
  // to make the example shorter
  const firstPage = pagesResponse.authorizedFacebookPages()[0]
  
  if (!firstPage) return null 

  const instagramAccountRequest = new GetLinkedInstagramAccountRequest(
    accessToken, firstPage.id
  )
  const instagramResponse = await instagramAccountRequest.execute()

  return instagramResponse.instagramPageId()
}
```

Now is when we can start publishing content on behave of the user. 😅 

## TODO
- [ ] Fix tests
- [ ] Fix documentation comments
- [ ] Finish adding documentation on the README.md to explain how to develop this lib

2021-07-18 13:42 UTC, TiagoGrosso commented
Hey @andresgutgon , thank you so much for this contribution! A couple of things:

- I'm going to be on holidays until July 23th, I'll test the functionality and fully review this then
- Do check this out: https://github.com/TiagoGrosso/instagram-graph-api-lib/blob/master/CONTRIBUTING.md
  - Don't forget to replace the `@author` tags
  - The `@since` tags should be replaced by ``  `next.release` ``
- Let's not add anything to the ReadMe about "Development" on this PR. I understand what you're getting at, and I'll add it to the `CONTRIBUTING.md` file once I get back

Once again thanks a lot for this 😀

2021-07-27 20:24 UTC, TiagoGrosso requested changes
Haven't tested the functionality of this yet, so for now I just left a few comments on style and other stuff. Don't forget to:

- Run the prettier format command (actually I recommend just adding the prettier extension to your IDE)
- Fix the tests and create tests for the new requests / responses

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/data/AuthorizedFacebookPagesData.ts
> + * @since next.release
Actually needs to be like this:

```suggestion
 * @since `next.release`
```

Same for other places

2021-07-27 20:24 UTC, TiagoGrosso commented on src/Index.ts.bak
> +
Not sure why this file exists now, but remove it 😛

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/data/InstagramAccountInfoData.ts
> + * for displaying in the UI what Account is linked in your app
```suggestion
 * for displaying in the UI what Account is linked in your app.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/authorized_facebook_pages/GetAuthorizedFacebookPagesResponse.ts
> +    public authorizedFacebookPages(): Array<FacebookPage> {
```suggestion
    public getAuthorizedFacebookPages(): Array<FacebookPage> {
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoRequest.ts
> + * @author Tiago Grosso <tiagogrosso99@gmail.com>
Dont forget to change the author and since tags here

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoRequest.ts
> +    instagramPageId: string
Comment explaining this field. Can be super basic, like on other requests

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoResponse.ts
> +    public accountInfo(): InstagramAccountInfoData {
```suggestion
    public getAccountInfo(): InstagramAccountInfoData {
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoResponse.ts
> +    /**
Missing a line saying "gets the data of the account"

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoResponse.ts
> +     * @returns the data of the account
```suggestion
     * @returns the data of the account.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> + * @author Tiago Grosso <tiagogrosso99@gmail.com>
author and sincetags

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> +    facebookPageId: string
comment for this field

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> +     * @param facebookPageId Facebook page where Instagram Account is linked
```suggestion
     * @param facebookPageId Facebook page where Instagram Account is linked.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> + * @author Tiago Grosso <tiagogrosso99@gmail.com>
author and since tags

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +    public instagramPageId(): string {
```suggestion
    public getInstagramPageId(): string {
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +     * Facebook requires Instagram accounts to be linked to a Facebook page and also
I'd change this to be something like:

"Gets the list of authorized facebook pages." and then add this explanation after that

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +     * @returns the list of authorized facebook pages
```suggestion
     * @returns the list of authorized facebook pages.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +     * endpoint will return linked Instagram Page ID
```suggestion
     * endpoint will return linked Instagram Page ID.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenRequest.ts
> + * https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/#get-a-long-lived-user-access-token
```suggestion
/**
 * This class is used to exchange a short-lived-token by a long-lived-token that you get when
 * the performs a Facebook login in your page and wants to authorize your app
 * to make requests for longer than a short-lived token's expiration.
 *
 * This long-lived-token last ~60 days according to Facebook documentation: https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/#get-a-long-lived-user-access-token
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenRequest.ts
> +const GRANT_TYPE = 'fb_exchange_token'
Comment to explain this

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenRequest.ts
> +     * @param appSecretId your App Secret Id
```suggestion
     * @param appSecretId your App Secret Id.
```

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenResponse.ts
> + *
Change this to simply be "Represents a response from the {@link GetUserLongLivedTokenRequest}"

2021-07-27 20:24 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenResponse.ts
> +     * @returns the user's long-lived access token
```suggestion
     * Gets user's long-lived-token.
     *
     * @returns the user's long-lived access token.
```

2021-07-31 13:08 UTC, andresgutgon commented
@TiagoGrosso I did the tests and fixed the documentation. Please let me know if you see it ok

2021-08-14 12:18 UTC, TiagoGrosso requested changes
@andresgutgon , I finally got around to testing this, sorry for the long delay but work has been hectic. Really great job, everything seems to work as expected ⭐ 

Left a few minor suggestions regarding comments/jsdocs and I'd also say that I think it would make sense that you add the "GetInstagramAccountInfoRequest" to the `Client.ts` (and add a test for it on `Client.test.ts`)

After that I'm ready to approve and merge this! 😃

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/data/AuthorizedFacebookPagesData.ts
> +export interface FacebookPage {
jsdocs for this interface

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/data/LinkedInstagramAccountData.ts
> +export interface LinkedInstagramAccountData {
jsdocs

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/authorized_facebook_pages/GetAuthorizedFacebookPagesResponse.ts
> + * Class that represents a response of user's Facebook pages
```suggestion
 * Class that represents a response of user's Facebook pages.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoRequest.ts
> + * A Get request to obtain Instagram account information.
```suggestion
 * A Get request to obtain information about an Instagram account.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/instagram_account_info/GetInstagramAccountInfoResponse.ts
> + * Class that represents a response from a Get Me request.
```suggestion
 * Class that represents a response from a Get Instagram Account Info request.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> + * a Facebock page
```suggestion
 * a Facebook page.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> +    // of an Instagram account you need the ID of their linked Facebook page.
```suggestion
   /**
   * The id of the Facebook page. A business Instagram account has to be linked to a Facebook page.
   */
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountRequest.ts
> +     * @param facebookPageId Facebook page where Instagram Account is linked.
Let's make it simple. From the name of the class people already get that this is all related to a linked Instagram page

```suggestion
     * @param facebookPageId the Facebook page id.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> + * Is used to get linked instagram account ID
```suggestion
 * Class that represents a response from a Get Linked Instagram page request
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +     * First gets the list of authorized facebook pages.
```suggestion
     * Gets the list of authorized facebook pages.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/linked_instagram_account/GetLinkedInstagramAccountResponse.ts
> +     * endpoint will return linked Instagram Page ID.
```suggestion
     * to be Instagram business accounts. If these conditions are met, this
     * request will return the linked Instagram Page ID.
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenRequest.ts
> +// using your app you need to request this type in the API
```suggestion
/**
*  When requesting a long-lived access token on behalf of the user that is
*  using your app, you need to request this type in the API
*/
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenRequest.ts
> + * the performs a Facebook login in your page and wants to authorize your app
```suggestion
 * the user performs a Facebook login in your page and wants to authorize your app
```

2021-08-14 12:18 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenResponse.ts
> + * Represents a response from the {@link GetUserLongLivedTokenRequest}"
Just for consistency with what I've been putting on other classes:

```suggestion
 * Represents a response from a Get UserLong Lived Token Request
```

2021-08-22 22:04 UTC, TiagoGrosso approved these changes

2021-08-22 22:05 UTC, TiagoGrosso commented on src/main/requests/page/user_long_lived_token/GetUserLongLivedTokenResponse.ts
> + * Represents a response from the {@link GetUserLongLivedTokenRequest}"
I had some time so I made the commit with the changes I request, pretty normal stuff. Also updated the readme. Thanks again for this 👍

2021-08-22 22:05 UTC, merged

2021-08-23 06:26 UTC, andresgutgon commented
Thanks 🙏 this month I'm offline